create database sales

CREATE TABLE sales_data (
    id INT  PRIMARY KEY,
    salesman VARCHAR(50) NOT NULL,
    product VARCHAR(50) NOT NULL,
    sale_date DATE NOT NULL,
    region VARCHAR(50) NOT NULL,
    hours INT NOT NULL,
    sales INT NOT NULL,
    sales_per_hour DECIMAL(10, 4) NOT NULL,
    revenue INT NOT NULL,
    revenue_per_hour DECIMAL(12, 4) NOT NULL,
    calls INT NOT NULL,
    excellent INT DEFAULT 0,
    good INT DEFAULT 0,
    fair INT DEFAULT 0,
    poor INT DEFAULT 0,
    total_feedback INT DEFAULT 0,
    client_satisfaction DECIMAL(5, 4) NOT NULL,
    positive INT DEFAULT 0,
    negative INT DEFAULT 0
);

-- Advanced SQL Questions
--The following questions fit this advanced report structure more meaningfully than a basic sales summary:

--	Which salesperson leads on revenue, revenue per hour, and conversion proxy, and do these leaders differ?                
--	Which salespeople perform above the team average on revenue, productivity, and satisfaction at the same time?           
--	Which salespeople fall into champion, loyal, at-risk, and hibernating RFM segments?          
--	What percentage of revenue is generated by the top 20 percent of performers?              
--	Which performers make up the first 80 percent of cumulative revenue?                    
--	At which funnel stage does the largest drop-off occur?                
--	Are high call volumes translating into high sales and high satisfaction, or only into activity?                  
--	How quickly does activity persistence decline across monthly cohorts?                    
--	Which product produces higher revenue per call and stronger satisfaction-adjusted performance?                  
--	Which region has low revenue but high satisfaction, indicating untapped opportunity?                    
--	Which salesperson creates strong revenue but weak customer quality, indicating sustainability risk?                 
--	Which performers should be rewarded, coached, or reassigned under a composite scorecard?                 

--SQL Query Set
--Revenue, Efficiency, and Conversion

SELECT
    Salesman,
    SUM(Revenue) AS total_revenue,
    SUM(Hours) AS total_hours,
    SUM(Calls) AS total_calls,
    SUM(Sales) AS total_units,
    SUM(Revenue) * 1.0 / NULLIF(SUM(Hours),0) AS revenue_per_hour,
    SUM(Sales) * 1.0 / NULLIF(SUM(Calls),0) AS conversion_proxy
FROM sales_dashboard
GROUP BY Salesman
ORDER BY total_revenue DESC;

--Team-Average Variance

WITH team_avg AS (
    SELECT
        AVG(Revenue * 1.0) AS avg_revenue,
        AVG(Revenue * 1.0 / NULLIF(Hours,0)) AS avg_rev_per_hour,
        AVG([Client Satisfaction] * 1.0) AS avg_satisfaction
    FROM sales_dashboard
)
SELECT
    Salesman,
    AVG(Revenue) AS avg_revenue_per_record,
    AVG(Revenue * 1.0 / NULLIF(Hours,0)) AS avg_rev_per_hour,
    AVG([Client Satisfaction] * 1.0) AS avg_satisfaction
FROM sales_dashboard, team_avg
GROUP BY Salesman, avg_revenue, avg_rev_per_hour, avg_satisfaction
HAVING AVG(Revenue) > avg_revenue
   AND AVG(Revenue * 1.0 / NULLIF(Hours,0)) > avg_rev_per_hour
   AND AVG([Client Satisfaction] * 1.0) > avg_satisfaction
ORDER BY avg_rev_per_hour DESC;

--RFM Base

WITH rfm_base AS (
    SELECT
        Salesman,
        DATEDIFF(DAY, MAX([Sale Date]), (SELECT DATEADD(DAY,1,MAX([Sale Date])) FROM sales_dashboard)) AS recency,
        COUNT(*) AS frequency,
        SUM(Revenue) AS monetary
    FROM sales_dashboard
    GROUP BY Salesman
)
SELECT *
FROM rfm_base
ORDER BY monetary DESC;


--Funnel Proxy

SELECT 'Total Records' AS funnel_stage, COUNT(*) AS record_count FROM sales_dashboard
UNION ALL
SELECT 'High Activity Calls (>300)', COUNT(*) FROM sales_dashboard WHERE Calls > 300
UNION ALL
SELECT 'High Sales (>30)', COUNT(*) FROM sales_dashboard WHERE Sales > 30
UNION ALL
SELECT 'High Revenue (>80000)', COUNT(*) FROM sales_dashboard WHERE Revenue > 80000
UNION ALL
SELECT 'High Satisfaction (>0.75)', COUNT(*) FROM sales_dashboard WHERE [Client Satisfaction] > 0.75;


--Cohort Setup

WITH base AS (
    SELECT
        Salesman,
        DATEFROMPARTS(YEAR([Sale Date]), MONTH([Sale Date]), 1) AS order_month,
        MIN(DATEFROMPARTS(YEAR([Sale Date]), MONTH([Sale Date]), 1)) OVER (PARTITION BY Salesman) AS cohort_month
    FROM sales_dashboard
),
cohort_data AS (
    SELECT
        Salesman,
        cohort_month,
        order_month,
        DATEDIFF(MONTH, cohort_month, order_month) AS cohort_index
    FROM base
)
SELECT cohort_month, cohort_index, COUNT(DISTINCT Salesman) AS active_salesmen
FROM cohort_data
GROUP BY cohort_month, cohort_index
ORDER BY cohort_month, cohort_index;

--Pareto Contribution

WITH perf AS (
    SELECT Salesman, SUM(Revenue) AS revenue
    FROM sales_dashboard
    GROUP BY Salesman
), ranked AS (
    SELECT
        Salesman,
        revenue,
        SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM perf
)
SELECT
    Salesman,
    revenue,
    cumulative_revenue,
    ROUND(100.0 * cumulative_revenue / total_revenue, 2) AS cumulative_pct
FROM ranked
ORDER BY revenue DESC;


--Quality Analysis

SELECT
    Salesman,
    SUM(Revenue) AS total_revenue,
    AVG([Client Satisfaction] * 1.0) AS avg_satisfaction,
    SUM(Positive) AS total_positive,
    SUM(Negative) AS total_negative
FROM sales_dashboard
GROUP BY Salesman
ORDER BY total_revenue DESC;


--Product Efficiency
SELECT
    Product,
    SUM(Revenue) AS total_revenue,
    SUM(Sales) AS total_units,
    SUM(Calls) AS total_calls,
    SUM(Revenue) * 1.0 / NULLIF(SUM(Calls),0) AS revenue_per_call,
    AVG([Client Satisfaction] * 1.0) AS avg_satisfaction
FROM sales_dashboard
GROUP BY Product
ORDER BY total_revenue DESC;

--Region Opportunity

SELECT
    Region,
    SUM(Revenue) AS total_revenue,
    SUM(Sales) AS total_units,
    AVG([Client Satisfaction] * 1.0) AS avg_satisfaction,
    SUM(Revenue) * 1.0 / NULLIF(SUM(Hours),0) AS revenue_per_hour
FROM sales_dashboard
GROUP BY Region
ORDER BY total_revenue DESC;


--Window Function Ranking

SELECT
    Salesman,
    Region,
    SUM(Revenue) AS total_revenue,
    RANK() OVER (PARTITION BY Region ORDER BY SUM(Revenue) DESC) AS regional_rank,
    ROUND(100.0 * SUM(Revenue) / SUM(SUM(Revenue)) OVER (), 2) AS revenue_share_pct
FROM sales_dashboard
GROUP BY Salesman, Region;

--Monthly Variance

WITH monthly AS (
    SELECT
        FORMAT([Sale Date], 'yyyy-MM') AS sale_month,
        SUM(Revenue) AS monthly_revenue
    FROM sales_dashboard
    GROUP BY FORMAT([Sale Date], 'yyyy-MM')
)
SELECT
    sale_month,
    monthly_revenue,
    LAG(monthly_revenue) OVER (ORDER BY sale_month) AS previous_month_revenue,
    monthly_revenue - LAG(monthly_revenue) OVER (ORDER BY sale_month) AS variance
FROM monthly
ORDER BY sale_month;


--Composite Performance Scorecard

WITH perf AS (
    SELECT
        Salesman,
        SUM(Revenue) AS revenue,
        SUM(Revenue) * 1.0 / NULLIF(SUM(Hours),0) AS revenue_per_hour,
        AVG([Client Satisfaction] * 1.0) AS satisfaction
    FROM sales_dashboard
    GROUP BY Salesman
)
SELECT
    Salesman,
    revenue,
    revenue_per_hour,
    satisfaction,
    DENSE_RANK() OVER (ORDER BY revenue DESC) AS revenue_rank,
    DENSE_RANK() OVER (ORDER BY revenue_per_hour DESC) AS efficiency_rank,
    DENSE_RANK() OVER (ORDER BY satisfaction DESC) AS satisfaction_rank
FROM perf
ORDER BY revenue_rank, efficiency_rank;




